spring.application.name=BillingAndCollections

# --- Logging ---
logging.level.root=INFO
logging.level.org.aaa.billingandcollections=INFO
logging.pattern.console=%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

# --- Scheduling ---
spring.task.scheduling.enabled=true


# --- Payment Retry ---
payment.retry.delay-ms=2000
payment.retry.max-attempts=2

# --- Scheduling ---
payment.dispatcher.fixed-delay-ms=1000
payment.worker.fixed-delay-ms=1000

